### ISSUE TITLE
显示 error Command failed with exit code 1.

### ISSUE THREAD

**Issue by gao507947164** [teamssix/twiki#71]
![image](https://github.com/teamssix/TWiki/assets/95402876/f7404c2c-a77e-404d-ba55-a77d60185f05)
而且dist目录下没有文件

**Comment by teamssix** [comment]
可以把问题描述的清楚些吗？

**Comment by gao507947164** [comment]
你好，我尝试在本地手动部署，根据教程的命令依次执行，但是运行yarn docs:build的时候就报了这个错误。

**Comment by teamssix** [comment]
我注意到网上有一些关于此问题的一些回答，因为我不清楚你那边本地的环境，也不确定网上的哪个回答对你有帮助，我建议你可以自行到网上搜索相关问题的答案，并尝试解决，或者直接使用 Docker 部署 T Wiki

**Comment by teamssix** [comment]
由于长时间未回复，此 issue 被关闭
